"""
locations_db.py
---------------
Full UK locations database for RemovalsNation.
Format per entry: (display_name, region, county, postcode_prefix, url_slug)

Run directly to generate /data/locations.json:
    python scripts/locations_db.py
"""

import json, os

ALL_LOCATIONS = [
    # ── GREATER LONDON — Boroughs ──────────────────────────────────────────────
    ("Camden","North London","Greater London","NW1","camden"),
    ("Islington","North London","Greater London","N1","islington"),
    ("Hackney","East London","Greater London","E8","hackney"),
    ("Tower Hamlets","East London","Greater London","E1","tower-hamlets"),
    ("Southwark","South London","Greater London","SE1","southwark"),
    ("Lambeth","South London","Greater London","SW2","lambeth"),
    ("Wandsworth","South West London","Greater London","SW18","wandsworth"),
    ("Hammersmith","West London","Greater London","W6","hammersmith"),
    ("Kensington","West London","Greater London","W8","kensington"),
    ("Westminster","Central London","Greater London","SW1","westminster"),
    ("Bromley","South East London","Greater London","BR1","bromley"),
    ("Croydon","South London","Greater London","CR0","croydon"),
    ("Greenwich","South East London","Greater London","SE10","greenwich"),
    ("Lewisham","South East London","Greater London","SE13","lewisham"),
    ("Bexley","South East London","Greater London","DA5","bexley"),
    ("Havering","East London","Greater London","RM1","havering"),
    ("Barking","East London","Greater London","IG11","barking"),
    ("Newham","East London","Greater London","E13","newham"),
    ("Waltham Forest","North East London","Greater London","E17","waltham-forest"),
    ("Redbridge","North East London","Greater London","IG1","redbridge"),
    ("Haringey","North London","Greater London","N8","haringey"),
    ("Enfield","North London","Greater London","EN1","enfield"),
    ("Barnet","North London","Greater London","N12","barnet"),
    ("Harrow","North West London","Greater London","HA1","harrow"),
    ("Brent","North West London","Greater London","HA9","brent"),
    ("Ealing","West London","Greater London","W5","ealing"),
    ("Hounslow","West London","Greater London","TW3","hounslow"),
    ("Richmond","South West London","Greater London","TW9","richmond"),
    ("Kingston upon Thames","South West London","Greater London","KT1","kingston-upon-thames"),
    ("Merton","South West London","Greater London","SW19","merton"),
    ("Sutton","South London","Greater London","SM1","sutton"),
    ("Hillingdon","West London","Greater London","UB8","hillingdon"),
    # ── GREATER LONDON — Neighbourhoods ───────────────────────────────────────
    ("Shoreditch","East London","Greater London","E1","shoreditch"),
    ("Canary Wharf","East London","Greater London","E14","canary-wharf"),
    ("Clapham","South London","Greater London","SW4","clapham"),
    ("Brixton","South London","Greater London","SW9","brixton"),
    ("Peckham","South East London","Greater London","SE15","peckham"),
    ("Dalston","East London","Greater London","E8","dalston"),
    ("Stratford","East London","Greater London","E15","stratford"),
    ("Bethnal Green","East London","Greater London","E2","bethnal-green"),
    ("Fulham","West London","Greater London","SW6","fulham"),
    ("Putney","South West London","Greater London","SW15","putney"),
    ("Wimbledon","South West London","Greater London","SW19","wimbledon"),
    ("Tooting","South London","Greater London","SW17","tooting"),
    ("Balham","South London","Greater London","SW12","balham"),
    ("Streatham","South London","Greater London","SW16","streatham"),
    ("Finsbury Park","North London","Greater London","N4","finsbury-park"),
    ("Stoke Newington","North London","Greater London","N16","stoke-newington"),
    ("Tottenham","North London","Greater London","N17","tottenham"),
    ("Wood Green","North London","Greater London","N22","wood-green"),
    ("Muswell Hill","North London","Greater London","N10","muswell-hill"),
    ("Highgate","North London","Greater London","N6","highgate"),
    ("Archway","North London","Greater London","N19","archway"),
    ("Kentish Town","North London","Greater London","NW5","kentish-town"),
    ("Holloway","North London","Greater London","N7","holloway"),
    ("Clapton","East London","Greater London","E5","clapton"),
    ("Homerton","East London","Greater London","E9","homerton"),
    ("Bow","East London","Greater London","E3","bow"),
    ("Mile End","East London","Greater London","E3","mile-end"),
    ("Whitechapel","East London","Greater London","E1","whitechapel"),
    ("Poplar","East London","Greater London","E14","poplar"),
    ("Limehouse","East London","Greater London","E14","limehouse"),
    ("Wapping","East London","Greater London","E1W","wapping"),
    ("Forest Gate","East London","Greater London","E7","forest-gate"),
    ("Manor Park","East London","Greater London","E12","manor-park"),
    ("Ilford","East London","Greater London","IG1","ilford"),
    ("Romford","East London","Greater London","RM1","romford"),
    ("Hornchurch","East London","Greater London","RM11","hornchurch"),
    ("Upminster","East London","Greater London","RM14","upminster"),
    ("Rainham","East London","Greater London","RM13","rainham"),
    ("Dagenham","East London","Greater London","RM9","dagenham"),
    ("Chingford","North East London","Greater London","E4","chingford"),
    ("Leytonstone","North East London","Greater London","E11","leytonstone"),
    ("Leyton","North East London","Greater London","E10","leyton"),
    ("Wanstead","North East London","Greater London","E11","wanstead"),
    ("South Woodford","North East London","Greater London","E18","south-woodford"),
    ("Woodford Green","North East London","Greater London","IG8","woodford-green"),
    ("Loughton","Essex","Essex","IG10","loughton"),
    ("Gants Hill","North East London","Greater London","IG2","gants-hill"),
    ("Barkingside","North East London","Greater London","IG6","barkingside"),
    ("Collier Row","East London","Greater London","RM5","collier-row"),
    ("Gidea Park","East London","Greater London","RM2","gidea-park"),
    ("Harold Wood","East London","Greater London","RM3","harold-wood"),
    ("Grays","Essex","Essex","RM17","grays"),
    ("Southgate","North London","Greater London","N14","southgate"),
    ("Palmers Green","North London","Greater London","N13","palmers-green"),
    ("Edmonton","North London","Greater London","N18","edmonton"),
    ("Winchmore Hill","North London","Greater London","N21","winchmore-hill"),
    ("East Barnet","North London","Greater London","EN4","east-barnet"),
    ("Friern Barnet","North London","Greater London","N11","friern-barnet"),
    ("East Finchley","North London","Greater London","N2","east-finchley"),
    ("Mill Hill","North London","Greater London","NW7","mill-hill"),
    ("Edgware","North London","Greater London","HA8","edgware"),
    ("Stanmore","North West London","Greater London","HA7","stanmore"),
    ("Queensbury","North West London","Greater London","HA3","queensbury"),
    ("Wembley","North West London","Greater London","HA0","wembley"),
    ("Greenford","West London","Greater London","UB6","greenford"),
    ("Northolt","West London","Greater London","UB5","northolt"),
    ("Hayes","West London","Greater London","UB3","hayes"),
    ("Southall","West London","Greater London","UB1","southall"),
    ("Hanwell","West London","Greater London","W7","hanwell"),
    ("Acton","West London","Greater London","W3","acton"),
    ("Chiswick","West London","Greater London","W4","chiswick"),
    ("Brentford","West London","Greater London","TW8","brentford"),
    ("Isleworth","West London","Greater London","TW7","isleworth"),
    ("Twickenham","South West London","Greater London","TW1","twickenham"),
    ("Teddington","South West London","Greater London","TW11","teddington"),
    ("Hampton","South West London","Greater London","TW12","hampton"),
    ("Surbiton","South West London","Greater London","KT6","surbiton"),
    ("New Malden","South West London","Greater London","KT3","new-malden"),
    ("Worcester Park","South West London","Greater London","KT4","worcester-park"),
    ("Cheam","South London","Greater London","SM3","cheam"),
    ("Carshalton","South London","Greater London","SM5","carshalton"),
    ("Wallington","South London","Greater London","SM6","wallington"),
    ("Mitcham","South West London","Greater London","CR4","mitcham"),
    ("Colliers Wood","South West London","Greater London","SW19","colliers-wood"),
    ("Norbury","South London","Greater London","SW16","norbury"),
    ("Thornton Heath","South London","Greater London","CR7","thornton-heath"),
    ("South Norwood","South London","Greater London","SE25","south-norwood"),
    ("Crystal Palace","South London","Greater London","SE19","crystal-palace"),
    ("Sydenham","South East London","Greater London","SE26","sydenham"),
    ("Forest Hill","South East London","Greater London","SE23","forest-hill"),
    ("Brockley","South East London","Greater London","SE4","brockley"),
    ("New Cross","South East London","Greater London","SE14","new-cross"),
    ("Deptford","South East London","Greater London","SE8","deptford"),
    ("Bermondsey","South London","Greater London","SE1","bermondsey"),
    ("Elephant and Castle","South London","Greater London","SE1","elephant-and-castle"),
    ("Kennington","South London","Greater London","SE11","kennington"),
    ("Stockwell","South London","Greater London","SW9","stockwell"),
    ("Vauxhall","South London","Greater London","SW8","vauxhall"),
    ("Battersea","South West London","Greater London","SW11","battersea"),
    ("Clapham Junction","South West London","Greater London","SW11","clapham-junction"),
    ("Earlsfield","South West London","Greater London","SW18","earlsfield"),
    ("Southfields","South West London","Greater London","SW18","southfields"),
    ("Raynes Park","South West London","Greater London","SW20","raynes-park"),
    ("Morden","South West London","Greater London","SM4","morden"),
    ("Norwood","South London","Greater London","SE27","norwood"),
    ("Tulse Hill","South London","Greater London","SE24","tulse-hill"),
    ("Herne Hill","South London","Greater London","SE24","herne-hill"),
    ("Dulwich","South East London","Greater London","SE21","dulwich"),
    ("East Dulwich","South East London","Greater London","SE22","east-dulwich"),
    ("Nunhead","South East London","Greater London","SE15","nunhead"),
    ("Catford","South East London","Greater London","SE6","catford"),
    ("Hither Green","South East London","Greater London","SE13","hither-green"),
    ("Eltham","South East London","Greater London","SE9","eltham"),
    ("Sidcup","South East London","Greater London","DA14","sidcup"),
    ("Chislehurst","South East London","Greater London","BR7","chislehurst"),
    ("Orpington","South East London","Greater London","BR6","orpington"),
    ("Petts Wood","South East London","Greater London","BR5","petts-wood"),
    ("Beckenham","South East London","Greater London","BR3","beckenham"),
    ("West Wickham","South East London","Greater London","BR4","west-wickham"),
    ("Addiscombe","South London","Greater London","CR0","addiscombe"),
    ("Shirley","South London","Greater London","CR0","shirley"),
    ("Purley","South London","Greater London","CR8","purley"),
    ("Coulsdon","South London","Greater London","CR5","coulsdon"),
    ("Belgravia","Central London","Greater London","SW1X","belgravia"),
    ("Pimlico","Central London","Greater London","SW1V","pimlico"),
    ("Mayfair","Central London","Greater London","W1K","mayfair"),
    ("Marylebone","Central London","Greater London","W1U","marylebone"),
    ("Soho","Central London","Greater London","W1D","soho"),
    ("Bloomsbury","Central London","Greater London","WC1","bloomsbury"),
    ("Clerkenwell","Central London","Greater London","EC1","clerkenwell"),
    ("Notting Hill","West London","Greater London","W11","notting-hill"),
    ("Holland Park","West London","Greater London","W11","holland-park"),
    ("Shepherds Bush","West London","Greater London","W12","shepherds-bush"),
    ("Kilburn","North West London","Greater London","NW6","kilburn"),
    ("West Hampstead","North West London","Greater London","NW6","west-hampstead"),
    ("Hampstead","North London","Greater London","NW3","hampstead"),
    ("Belsize Park","North London","Greater London","NW3","belsize-park"),
    ("Swiss Cottage","North London","Greater London","NW3","swiss-cottage"),
    ("St Johns Wood","North London","Greater London","NW8","st-johns-wood"),
    ("Maida Vale","West London","Greater London","W9","maida-vale"),
    ("Paddington","West London","Greater London","W2","paddington"),
    ("Bayswater","West London","Greater London","W2","bayswater"),
    ("Earls Court","West London","Greater London","SW5","earls-court"),
    ("Chelsea","West London","Greater London","SW3","chelsea"),
    ("South Kensington","West London","Greater London","SW7","south-kensington"),
    ("Knightsbridge","West London","Greater London","SW1X","knightsbridge"),
    ("Victoria","Central London","Greater London","SW1E","victoria"),
    ("Waterloo","South London","Greater London","SE1","waterloo"),
    ("London Bridge","South London","Greater London","SE1","london-bridge"),
    ("Hoxton","East London","Greater London","N1","hoxton"),
    ("Old Street","East London","Greater London","EC1V","old-street"),
    ("Angel","North London","Greater London","N1","angel"),
    ("Highbury","North London","Greater London","N5","highbury"),
    ("Crouch End","North London","Greater London","N8","crouch-end"),
    ("Alexandra Palace","North London","Greater London","N22","alexandra-palace"),
    ("Golders Green","North London","Greater London","NW11","golders-green"),
    ("Hendon","North London","Greater London","NW4","hendon"),
    ("Cricklewood","North West London","Greater London","NW2","cricklewood"),
    ("Tufnell Park","North London","Greater London","N7","tufnell-park"),
    ("London Fields","East London","Greater London","E8","london-fields"),
    ("Victoria Park","East London","Greater London","E9","victoria-park"),
    ("Hackney Wick","East London","Greater London","E9","hackney-wick"),
    ("Plaistow","East London","Greater London","E13","plaistow"),
    ("West Ham","East London","Greater London","E15","west-ham"),
    ("Upton Park","East London","Greater London","E13","upton-park"),
    ("East Ham","East London","Greater London","E6","east-ham"),
    ("Canning Town","East London","Greater London","E16","canning-town"),
    ("Woolwich","South East London","Greater London","SE18","woolwich"),
    ("Plumstead","South East London","Greater London","SE18","plumstead"),
    ("Abbey Wood","South East London","Greater London","SE2","abbey-wood"),
    ("Erith","South East London","Greater London","DA8","erith"),
    ("Welling","South East London","Greater London","DA16","welling"),
    ("Bexleyheath","South East London","Greater London","DA7","bexleyheath"),
    ("Crayford","South East London","Greater London","DA1","crayford"),
    ("Swanley","Kent","Kent","BR8","swanley"),
    ("Chigwell","Essex","Essex","IG7","chigwell"),
    ("Walthamstow","North East London","Greater London","E17","walthamstow"),
    ("Penge","South East London","Greater London","SE20","penge"),
    ("Blackheath","South East London","Greater London","SE3","blackheath"),
    ("Charlton","South East London","Greater London","SE7","charlton"),
    ("Thamesmead","South East London","Greater London","SE28","thamesmead"),
    ("Camberwell","South London","Greater London","SE5","camberwell"),
    ("Walworth","South London","Greater London","SE17","walworth"),
    ("Rotherhithe","South East London","Greater London","SE16","rotherhithe"),
    ("Canada Water","South East London","Greater London","SE16","canada-water"),
    ("Isle of Dogs","East London","Greater London","E14","isle-of-dogs"),
    ("Spitalfields","East London","Greater London","E1","spitalfields"),
    ("Shadwell","East London","Greater London","E1","shadwell"),
    ("Stepney Green","East London","Greater London","E1","stepney-green"),
    ("Silvertown","East London","Greater London","E16","silvertown"),
    ("Chadwell Heath","East London","Greater London","RM6","chadwell-heath"),
    ("New Addington","South London","Greater London","CR0","new-addington"),
    ("South Croydon","South London","Greater London","CR2","south-croydon"),
    ("East Croydon","South London","Greater London","CR0","east-croydon"),
    # ── SURREY ────────────────────────────────────────────────────────────────
    ("Guildford","Surrey","Surrey","GU1","guildford"),
    ("Woking","Surrey","Surrey","GU21","woking"),
    ("Epsom","Surrey","Surrey","KT17","epsom"),
    ("Redhill","Surrey","Surrey","RH1","redhill"),
    ("Reigate","Surrey","Surrey","RH2","reigate"),
    ("Leatherhead","Surrey","Surrey","KT22","leatherhead"),
    ("Esher","Surrey","Surrey","KT10","esher"),
    ("Staines-upon-Thames","Surrey","Surrey","TW18","staines-upon-thames"),
    ("Camberley","Surrey","Surrey","GU15","camberley"),
    ("Farnham","Surrey","Surrey","GU9","farnham"),
    ("Dorking","Surrey","Surrey","RH4","dorking"),
    ("Godalming","Surrey","Surrey","GU7","godalming"),
    ("Haslemere","Surrey","Surrey","GU27","haslemere"),
    ("Cranleigh","Surrey","Surrey","GU6","cranleigh"),
    ("Horley","Surrey","Surrey","RH6","horley"),
    ("Caterham","Surrey","Surrey","CR3","caterham"),
    ("Oxted","Surrey","Surrey","RH8","oxted"),
    ("Weybridge","Surrey","Surrey","KT13","weybridge"),
    ("Walton-on-Thames","Surrey","Surrey","KT12","walton-on-thames"),
    ("Cobham","Surrey","Surrey","KT11","cobham"),
    ("Chertsey","Surrey","Surrey","KT16","chertsey"),
    ("Addlestone","Surrey","Surrey","KT15","addlestone"),
    ("Virginia Water","Surrey","Surrey","GU25","virginia-water"),
    ("Egham","Surrey","Surrey","TW20","egham"),
    ("Sunbury-on-Thames","Surrey","Surrey","TW16","sunbury-on-thames"),
    ("Shepperton","Surrey","Surrey","TW17","shepperton"),
    ("Thames Ditton","Surrey","Surrey","KT7","thames-ditton"),
    ("Ewell","Surrey","Surrey","KT17","ewell"),
    ("Ashtead","Surrey","Surrey","KT21","ashtead"),
    ("Fetcham","Surrey","Surrey","KT22","fetcham"),
    ("Great Bookham","Surrey","Surrey","KT23","great-bookham"),
    ("Byfleet","Surrey","Surrey","KT14","byfleet"),
    ("West Byfleet","Surrey","Surrey","KT14","west-byfleet"),
    ("Frimley","Surrey","Surrey","GU16","frimley"),
    ("Ash","Surrey","Surrey","GU12","ash"),
    ("Bagshot","Surrey","Surrey","GU19","bagshot"),
    ("Lightwater","Surrey","Surrey","GU18","lightwater"),
    ("Tadworth","Surrey","Surrey","KT20","tadworth"),
    ("Kingswood Surrey","Surrey","Surrey","KT20","kingswood-surrey"),
    ("Chipstead","Surrey","Surrey","CR5","chipstead"),
    ("Lingfield","Surrey","Surrey","RH7","lingfield"),
    # ── HERTFORDSHIRE ─────────────────────────────────────────────────────────
    ("Watford","Hertfordshire","Hertfordshire","WD17","watford"),
    ("St Albans","Hertfordshire","Hertfordshire","AL1","st-albans"),
    ("Hemel Hempstead","Hertfordshire","Hertfordshire","HP1","hemel-hempstead"),
    ("Stevenage","Hertfordshire","Hertfordshire","SG1","stevenage"),
    ("Hatfield","Hertfordshire","Hertfordshire","AL10","hatfield"),
    ("Welwyn Garden City","Hertfordshire","Hertfordshire","AL7","welwyn-garden-city"),
    ("Hertford","Hertfordshire","Hertfordshire","SG13","hertford"),
    ("Ware","Hertfordshire","Hertfordshire","SG12","ware"),
    ("Bishops Stortford","Hertfordshire","Hertfordshire","CM23","bishops-stortford"),
    ("Hoddesdon","Hertfordshire","Hertfordshire","EN11","hoddesdon"),
    ("Broxbourne","Hertfordshire","Hertfordshire","EN10","broxbourne"),
    ("Waltham Cross","Hertfordshire","Hertfordshire","EN8","waltham-cross"),
    ("Cheshunt","Hertfordshire","Hertfordshire","EN8","cheshunt"),
    ("Potters Bar","Hertfordshire","Hertfordshire","EN6","potters-bar"),
    ("Borehamwood","Hertfordshire","Hertfordshire","WD6","borehamwood"),
    ("Radlett","Hertfordshire","Hertfordshire","WD7","radlett"),
    ("Harpenden","Hertfordshire","Hertfordshire","AL5","harpenden"),
    ("Hitchin","Hertfordshire","Hertfordshire","SG5","hitchin"),
    ("Letchworth Garden City","Hertfordshire","Hertfordshire","SG6","letchworth-garden-city"),
    ("Baldock","Hertfordshire","Hertfordshire","SG7","baldock"),
    ("Royston","Hertfordshire","Hertfordshire","SG8","royston"),
    ("Tring","Hertfordshire","Hertfordshire","HP23","tring"),
    ("Berkhamsted","Hertfordshire","Hertfordshire","HP4","berkhamsted"),
    ("Kings Langley","Hertfordshire","Hertfordshire","WD4","kings-langley"),
    ("Abbots Langley","Hertfordshire","Hertfordshire","WD5","abbots-langley"),
    ("Bushey","Hertfordshire","Hertfordshire","WD23","bushey"),
    ("Rickmansworth","Hertfordshire","Hertfordshire","WD3","rickmansworth"),
    ("Chorleywood","Hertfordshire","Hertfordshire","WD3","chorleywood"),
    ("Northwood","Hertfordshire","Hertfordshire","HA6","northwood"),
    # ── ESSEX ─────────────────────────────────────────────────────────────────
    ("Chelmsford","Essex","Essex","CM1","chelmsford"),
    ("Colchester","Essex","Essex","CO1","colchester"),
    ("Southend-on-Sea","Essex","Essex","SS1","southend-on-sea"),
    ("Basildon","Essex","Essex","SS14","basildon"),
    ("Braintree","Essex","Essex","CM7","braintree"),
    ("Brentwood","Essex","Essex","CM14","brentwood"),
    ("Clacton-on-Sea","Essex","Essex","CO15","clacton-on-sea"),
    ("Thurrock","Essex","Essex","RM20","thurrock"),
    ("Witham","Essex","Essex","CM8","witham"),
    ("Maldon","Essex","Essex","CM9","maldon"),
    ("Saffron Walden","Essex","Essex","CB10","saffron-walden"),
    ("Harwich","Essex","Essex","CO12","harwich"),
    ("Rayleigh","Essex","Essex","SS6","rayleigh"),
    ("Rochford","Essex","Essex","SS4","rochford"),
    ("Wickford","Essex","Essex","SS12","wickford"),
    ("Billericay","Essex","Essex","CM12","billericay"),
    ("Shenfield","Essex","Essex","CM15","shenfield"),
    ("Ingatestone","Essex","Essex","CM4","ingatestone"),
    ("South Woodham Ferrers","Essex","Essex","CM3","south-woodham-ferrers"),
    ("Burnham-on-Crouch","Essex","Essex","CM0","burnham-on-crouch"),
    ("Canvey Island","Essex","Essex","SS8","canvey-island"),
    ("Stanford-le-Hope","Essex","Essex","SS17","stanford-le-hope"),
    ("Harlow","Essex","Essex","CM20","harlow"),
    ("Epping","Essex","Essex","CM16","epping"),
    ("Chafford Hundred","Essex","Essex","RM16","chafford-hundred"),
    # ── KENT ──────────────────────────────────────────────────────────────────
    ("Canterbury","Kent","Kent","CT1","canterbury"),
    ("Maidstone","Kent","Kent","ME14","maidstone"),
    ("Medway","Kent","Kent","ME1","medway"),
    ("Tunbridge Wells","Kent","Kent","TN1","tunbridge-wells"),
    ("Folkestone","Kent","Kent","CT20","folkestone"),
    ("Dartford","Kent","Kent","DA1","dartford"),
    ("Sevenoaks","Kent","Kent","TN13","sevenoaks"),
    ("Ashford","Kent","Kent","TN23","ashford"),
    ("Margate","Kent","Kent","CT9","margate"),
    ("Ramsgate","Kent","Kent","CT11","ramsgate"),
    ("Broadstairs","Kent","Kent","CT10","broadstairs"),
    ("Dover","Kent","Kent","CT16","dover"),
    ("Deal","Kent","Kent","CT14","deal"),
    ("Whitstable","Kent","Kent","CT5","whitstable"),
    ("Herne Bay","Kent","Kent","CT6","herne-bay"),
    ("Faversham","Kent","Kent","ME13","faversham"),
    ("Sittingbourne","Kent","Kent","ME10","sittingbourne"),
    ("Gillingham","Kent","Kent","ME7","gillingham"),
    ("Rochester","Kent","Kent","ME1","rochester"),
    ("Chatham","Kent","Kent","ME4","chatham"),
    ("Gravesend","Kent","Kent","DA11","gravesend"),
    ("Tonbridge","Kent","Kent","TN9","tonbridge"),
    ("Paddock Wood","Kent","Kent","TN12","paddock-wood"),
    ("Cranbrook","Kent","Kent","TN17","cranbrook"),
    ("Tenterden","Kent","Kent","TN30","tenterden"),
    ("Hythe","Kent","Kent","CT21","hythe"),
    ("West Malling","Kent","Kent","ME19","west-malling"),
    ("Kings Hill","Kent","Kent","ME19","kings-hill"),
    ("Snodland","Kent","Kent","ME6","snodland"),
    ("Strood","Kent","Kent","ME2","strood"),
    ("Edenbridge","Kent","Kent","TN8","edenbridge"),
    ("Borough Green","Kent","Kent","TN15","borough-green"),
    ("Pembury","Kent","Kent","TN2","pembury"),
    # ── EAST SUSSEX ───────────────────────────────────────────────────────────
    ("Brighton","East Sussex","East Sussex","BN1","brighton"),
    ("Hove","East Sussex","East Sussex","BN3","hove"),
    ("Eastbourne","East Sussex","East Sussex","BN21","eastbourne"),
    ("Hastings","East Sussex","East Sussex","TN34","hastings"),
    ("Lewes","East Sussex","East Sussex","BN7","lewes"),
    ("Newhaven","East Sussex","East Sussex","BN9","newhaven"),
    ("Seaford","East Sussex","East Sussex","BN25","seaford"),
    ("Peacehaven","East Sussex","East Sussex","BN10","peacehaven"),
    ("Bexhill-on-Sea","East Sussex","East Sussex","TN39","bexhill-on-sea"),
    ("Rye","East Sussex","East Sussex","TN31","rye"),
    ("Uckfield","East Sussex","East Sussex","TN22","uckfield"),
    ("Crowborough","East Sussex","East Sussex","TN6","crowborough"),
    ("Hailsham","East Sussex","East Sussex","BN27","hailsham"),
    ("Polegate","East Sussex","East Sussex","BN26","polegate"),
    ("St Leonards-on-Sea","East Sussex","East Sussex","TN37","st-leonards-on-sea"),
    ("Shoreham-by-Sea","West Sussex","West Sussex","BN43","shoreham-by-sea"),
    ("Lancing","West Sussex","West Sussex","BN15","lancing"),
    ("Saltdean","East Sussex","East Sussex","BN2","saltdean"),
    # ── WEST SUSSEX ───────────────────────────────────────────────────────────
    ("Crawley","West Sussex","West Sussex","RH10","crawley"),
    ("Worthing","West Sussex","West Sussex","BN11","worthing"),
    ("Chichester","West Sussex","West Sussex","PO19","chichester"),
    ("Horsham","West Sussex","West Sussex","RH12","horsham"),
    ("Haywards Heath","West Sussex","West Sussex","RH16","haywards-heath"),
    ("Burgess Hill","West Sussex","West Sussex","RH15","burgess-hill"),
    ("Bognor Regis","West Sussex","West Sussex","PO21","bognor-regis"),
    ("Littlehampton","West Sussex","West Sussex","BN17","littlehampton"),
    ("Arundel","West Sussex","West Sussex","BN18","arundel"),
    ("East Grinstead","West Sussex","West Sussex","RH19","east-grinstead"),
    ("Steyning","West Sussex","West Sussex","BN44","steyning"),
    ("Henfield","West Sussex","West Sussex","BN5","henfield"),
    ("Hurstpierpoint","West Sussex","West Sussex","BN6","hurstpierpoint"),
    ("Hassocks","West Sussex","West Sussex","BN6","hassocks"),
    # ── BERKSHIRE ─────────────────────────────────────────────────────────────
    ("Reading","Berkshire","Berkshire","RG1","reading"),
    ("Slough","Berkshire","Berkshire","SL1","slough"),
    ("Windsor","Berkshire","Berkshire","SL4","windsor"),
    ("Maidenhead","Berkshire","Berkshire","SL6","maidenhead"),
    ("Bracknell","Berkshire","Berkshire","RG12","bracknell"),
    ("Newbury","Berkshire","Berkshire","RG14","newbury"),
    ("Wokingham","Berkshire","Berkshire","RG40","wokingham"),
    ("Sandhurst","Berkshire","Berkshire","GU47","sandhurst"),
    ("Thatcham","Berkshire","Berkshire","RG19","thatcham"),
    ("Caversham","Berkshire","Berkshire","RG4","caversham"),
    ("Earley","Berkshire","Berkshire","RG6","earley"),
    ("Woodley","Berkshire","Berkshire","RG5","woodley"),
    ("Twyford","Berkshire","Berkshire","RG10","twyford"),
    ("Ascot","Berkshire","Berkshire","SL5","ascot"),
    ("Sunningdale","Berkshire","Berkshire","SL5","sunningdale"),
    ("Tilehurst","Berkshire","Berkshire","RG30","tilehurst"),
    ("Burnham","Berkshire","Berkshire","SL1","burnham"),
    ("Datchet","Berkshire","Berkshire","SL3","datchet"),
    # ── OXFORDSHIRE ───────────────────────────────────────────────────────────
    ("Oxford","Oxfordshire","Oxfordshire","OX1","oxford"),
    ("Banbury","Oxfordshire","Oxfordshire","OX16","banbury"),
    ("Abingdon","Oxfordshire","Oxfordshire","OX14","abingdon"),
    ("Witney","Oxfordshire","Oxfordshire","OX28","witney"),
    ("Bicester","Oxfordshire","Oxfordshire","OX26","bicester"),
    ("Didcot","Oxfordshire","Oxfordshire","OX11","didcot"),
    ("Wantage","Oxfordshire","Oxfordshire","OX12","wantage"),
    ("Chipping Norton","Oxfordshire","Oxfordshire","OX7","chipping-norton"),
    ("Woodstock","Oxfordshire","Oxfordshire","OX20","woodstock"),
    ("Carterton","Oxfordshire","Oxfordshire","OX18","carterton"),
    ("Kidlington","Oxfordshire","Oxfordshire","OX5","kidlington"),
    ("Headington","Oxfordshire","Oxfordshire","OX3","headington"),
    ("Cowley","Oxfordshire","Oxfordshire","OX4","cowley"),
    ("Henley-on-Thames","Oxfordshire","Oxfordshire","RG9","henley-on-thames"),
    ("Thame","Oxfordshire","Oxfordshire","OX9","thame"),
    ("Wallingford","Oxfordshire","Oxfordshire","OX10","wallingford"),
    # ── BUCKINGHAMSHIRE ───────────────────────────────────────────────────────
    ("Milton Keynes","Buckinghamshire","Buckinghamshire","MK9","milton-keynes"),
    ("Aylesbury","Buckinghamshire","Buckinghamshire","HP20","aylesbury"),
    ("High Wycombe","Buckinghamshire","Buckinghamshire","HP11","high-wycombe"),
    ("Amersham","Buckinghamshire","Buckinghamshire","HP6","amersham"),
    ("Chesham","Buckinghamshire","Buckinghamshire","HP5","chesham"),
    ("Buckingham","Buckinghamshire","Buckinghamshire","MK18","buckingham"),
    ("Newport Pagnell","Buckinghamshire","Buckinghamshire","MK16","newport-pagnell"),
    ("Bletchley","Buckinghamshire","Buckinghamshire","MK2","bletchley"),
    ("Wolverton","Buckinghamshire","Buckinghamshire","MK12","wolverton"),
    ("Princes Risborough","Buckinghamshire","Buckinghamshire","HP27","princes-risborough"),
    ("Wendover","Buckinghamshire","Buckinghamshire","HP22","wendover"),
    ("Beaconsfield","Buckinghamshire","Buckinghamshire","HP9","beaconsfield"),
    ("Marlow","Buckinghamshire","Buckinghamshire","SL7","marlow"),
    ("Gerrards Cross","Buckinghamshire","Buckinghamshire","SL9","gerrards-cross"),
    ("Iver","Buckinghamshire","Buckinghamshire","SL0","iver"),
    # ── CAMBRIDGESHIRE ────────────────────────────────────────────────────────
    ("Cambridge","Cambridgeshire","Cambridgeshire","CB1","cambridge"),
    ("Peterborough","Cambridgeshire","Cambridgeshire","PE1","peterborough"),
    ("Ely","Cambridgeshire","Cambridgeshire","CB7","ely"),
    ("Huntingdon","Cambridgeshire","Cambridgeshire","PE29","huntingdon"),
    ("St Ives","Cambridgeshire","Cambridgeshire","PE27","st-ives"),
    ("St Neots","Cambridgeshire","Cambridgeshire","PE19","st-neots"),
    ("March","Cambridgeshire","Cambridgeshire","PE15","march"),
    ("Wisbech","Cambridgeshire","Cambridgeshire","PE13","wisbech"),
    ("Soham","Cambridgeshire","Cambridgeshire","CB7","soham"),
    ("Ramsey","Cambridgeshire","Cambridgeshire","PE26","ramsey"),
    ("Whittlesey","Cambridgeshire","Cambridgeshire","PE7","whittlesey"),
    ("Yaxley","Cambridgeshire","Cambridgeshire","PE7","yaxley"),
    ("Histon","Cambridgeshire","Cambridgeshire","CB24","histon"),
    # ── BEDFORDSHIRE ──────────────────────────────────────────────────────────
    ("Luton","Bedfordshire","Bedfordshire","LU1","luton"),
    ("Bedford","Bedfordshire","Bedfordshire","MK40","bedford"),
    ("Dunstable","Bedfordshire","Bedfordshire","LU5","dunstable"),
    ("Leighton Buzzard","Bedfordshire","Bedfordshire","LU7","leighton-buzzard"),
    ("Biggleswade","Bedfordshire","Bedfordshire","SG18","biggleswade"),
    ("Sandy","Bedfordshire","Bedfordshire","SG19","sandy"),
    ("Flitwick","Bedfordshire","Bedfordshire","MK45","flitwick"),
    ("Ampthill","Bedfordshire","Bedfordshire","MK45","ampthill"),
    ("Kempston","Bedfordshire","Bedfordshire","MK42","kempston"),
    ("Houghton Regis","Bedfordshire","Bedfordshire","LU5","houghton-regis"),
    # ── NORTHAMPTONSHIRE ──────────────────────────────────────────────────────
    ("Northampton","Northamptonshire","Northamptonshire","NN1","northampton"),
    ("Kettering","Northamptonshire","Northamptonshire","NN15","kettering"),
    ("Corby","Northamptonshire","Northamptonshire","NN17","corby"),
    ("Wellingborough","Northamptonshire","Northamptonshire","NN8","wellingborough"),
    ("Rushden","Northamptonshire","Northamptonshire","NN10","rushden"),
    ("Daventry","Northamptonshire","Northamptonshire","NN11","daventry"),
    ("Towcester","Northamptonshire","Northamptonshire","NN12","towcester"),
    # ── HAMPSHIRE ─────────────────────────────────────────────────────────────
    ("Southampton","Hampshire","Hampshire","SO14","southampton"),
    ("Portsmouth","Hampshire","Hampshire","PO1","portsmouth"),
    ("Winchester","Hampshire","Hampshire","SO23","winchester"),
    ("Basingstoke","Hampshire","Hampshire","RG21","basingstoke"),
    ("Eastleigh","Hampshire","Hampshire","SO50","eastleigh"),
    ("Fareham","Hampshire","Hampshire","PO16","fareham"),
    ("Gosport","Hampshire","Hampshire","PO12","gosport"),
    ("Andover","Hampshire","Hampshire","SP10","andover"),
    ("Havant","Hampshire","Hampshire","PO9","havant"),
    ("Waterlooville","Hampshire","Hampshire","PO7","waterlooville"),
    ("Romsey","Hampshire","Hampshire","SO51","romsey"),
    ("Chandlers Ford","Hampshire","Hampshire","SO53","chandlers-ford"),
    ("Hedge End","Hampshire","Hampshire","SO30","hedge-end"),
    ("Totton","Hampshire","Hampshire","SO40","totton"),
    ("Lymington","Hampshire","Hampshire","SO41","lymington"),
    ("New Milton","Hampshire","Hampshire","BH25","new-milton"),
    ("Ringwood","Hampshire","Hampshire","BH24","ringwood"),
    ("Farnborough","Hampshire","Hampshire","GU14","farnborough"),
    ("Fleet","Hampshire","Hampshire","GU51","fleet"),
    ("Aldershot","Hampshire","Hampshire","GU11","aldershot"),
    ("Yateley","Hampshire","Hampshire","GU46","yateley"),
    ("Petersfield","Hampshire","Hampshire","GU31","petersfield"),
    ("Alton","Hampshire","Hampshire","GU34","alton"),
    ("Bordon","Hampshire","Hampshire","GU35","bordon"),
    ("Whitchurch","Hampshire","Hampshire","RG28","whitchurch"),
    ("Hook","Hampshire","Hampshire","RG27","hook"),
    ("Emsworth","Hampshire","Hampshire","PO10","emsworth"),
    ("Ryde","Isle of Wight","Isle of Wight","PO33","ryde"),
    ("Newport IOW","Isle of Wight","Isle of Wight","PO30","newport-iow"),
    ("Cowes","Isle of Wight","Isle of Wight","PO31","cowes"),
    ("Sandown","Isle of Wight","Isle of Wight","PO36","sandown"),
    # ── DORSET ────────────────────────────────────────────────────────────────
    ("Bournemouth","Dorset","Dorset","BH1","bournemouth"),
    ("Poole","Dorset","Dorset","BH15","poole"),
    ("Weymouth","Dorset","Dorset","DT4","weymouth"),
    ("Dorchester","Dorset","Dorset","DT1","dorchester"),
    ("Bridport","Dorset","Dorset","DT6","bridport"),
    ("Blandford Forum","Dorset","Dorset","DT11","blandford-forum"),
    ("Wareham","Dorset","Dorset","BH20","wareham"),
    ("Swanage","Dorset","Dorset","BH19","swanage"),
    ("Wimborne Minster","Dorset","Dorset","BH21","wimborne-minster"),
    ("Ferndown","Dorset","Dorset","BH22","ferndown"),
    ("Christchurch","Dorset","Dorset","BH23","christchurch"),
    ("Sherborne","Dorset","Dorset","DT9","sherborne"),
    ("Shaftesbury","Dorset","Dorset","SP7","shaftesbury"),
    # ── WILTSHIRE ─────────────────────────────────────────────────────────────
    ("Swindon","Wiltshire","Wiltshire","SN1","swindon"),
    ("Salisbury","Wiltshire","Wiltshire","SP1","salisbury"),
    ("Chippenham","Wiltshire","Wiltshire","SN15","chippenham"),
    ("Trowbridge","Wiltshire","Wiltshire","BA14","trowbridge"),
    ("Devizes","Wiltshire","Wiltshire","SN10","devizes"),
    ("Melksham","Wiltshire","Wiltshire","SN12","melksham"),
    ("Marlborough","Wiltshire","Wiltshire","SN8","marlborough"),
    ("Calne","Wiltshire","Wiltshire","SN11","calne"),
    ("Bradford on Avon","Wiltshire","Wiltshire","BA15","bradford-on-avon"),
    ("Corsham","Wiltshire","Wiltshire","SN13","corsham"),
    ("Warminster","Wiltshire","Wiltshire","BA12","warminster"),
    ("Westbury","Wiltshire","Wiltshire","BA13","westbury"),
    ("Amesbury","Wiltshire","Wiltshire","SP4","amesbury"),
    ("Pewsey","Wiltshire","Wiltshire","SN9","pewsey"),
    # ── SOMERSET ──────────────────────────────────────────────────────────────
    ("Taunton","Somerset","Somerset","TA1","taunton"),
    ("Bath","Somerset","Somerset","BA1","bath"),
    ("Yeovil","Somerset","Somerset","BA20","yeovil"),
    ("Weston-super-Mare","Somerset","Somerset","BS23","weston-super-mare"),
    ("Bridgwater","Somerset","Somerset","TA6","bridgwater"),
    ("Frome","Somerset","Somerset","BA11","frome"),
    ("Glastonbury","Somerset","Somerset","BA6","glastonbury"),
    ("Wells","Somerset","Somerset","BA5","wells"),
    ("Chard","Somerset","Somerset","TA20","chard"),
    ("Minehead","Somerset","Somerset","TA24","minehead"),
    ("Burnham-on-Sea","Somerset","Somerset","TA8","burnham-on-sea"),
    ("Street","Somerset","Somerset","BA16","street"),
    ("Wellington","Somerset","Somerset","TA21","wellington"),
    ("Shepton Mallet","Somerset","Somerset","BA4","shepton-mallet"),
    ("Ilminster","Somerset","Somerset","TA19","ilminster"),
    ("Crewkerne","Somerset","Somerset","TA18","crewkerne"),
    ("Keynsham","Somerset","Somerset","BS31","keynsham"),
    ("Portishead","Somerset","Somerset","BS20","portishead"),
    ("Clevedon","Somerset","Somerset","BS21","clevedon"),
    ("Nailsea","Somerset","Somerset","BS48","nailsea"),
    ("Cheddar","Somerset","Somerset","BS27","cheddar"),
    # ── GLOUCESTERSHIRE ───────────────────────────────────────────────────────
    ("Bristol","Gloucestershire","South West England","BS1","bristol"),
    ("Cheltenham","Gloucestershire","Gloucestershire","GL50","cheltenham"),
    ("Gloucester","Gloucestershire","Gloucestershire","GL1","gloucester"),
    ("Stroud","Gloucestershire","Gloucestershire","GL5","stroud"),
    ("Cirencester","Gloucestershire","Gloucestershire","GL7","cirencester"),
    ("Tewkesbury","Gloucestershire","Gloucestershire","GL20","tewkesbury"),
    ("Dursley","Gloucestershire","Gloucestershire","GL11","dursley"),
    ("Coleford","Gloucestershire","Gloucestershire","GL16","coleford"),
    ("Cinderford","Gloucestershire","Gloucestershire","GL14","cinderford"),
    ("Lydney","Gloucestershire","Gloucestershire","GL15","lydney"),
    ("Moreton-in-Marsh","Gloucestershire","Gloucestershire","GL56","moreton-in-marsh"),
    ("Tetbury","Gloucestershire","Gloucestershire","GL8","tetbury"),
    ("Wotton-under-Edge","Gloucestershire","Gloucestershire","GL12","wotton-under-edge"),
    ("Thornbury","Gloucestershire","Gloucestershire","BS35","thornbury"),
    ("Yate","Gloucestershire","Gloucestershire","BS37","yate"),
    ("Chipping Sodbury","Gloucestershire","Gloucestershire","BS37","chipping-sodbury"),
    ("Filton","Gloucestershire","Gloucestershire","BS34","filton"),
    ("Kingswood Bristol","Gloucestershire","Gloucestershire","BS15","kingswood-bristol"),
    ("Bradley Stoke","Gloucestershire","Gloucestershire","BS32","bradley-stoke"),
    ("Patchway","Gloucestershire","Gloucestershire","BS34","patchway"),
    ("Westbury on Trym","Gloucestershire","Gloucestershire","BS9","westbury-on-trym"),
    ("Portishead","Gloucestershire","Gloucestershire","BS20","portishead-glos"),
    # ── DEVON ─────────────────────────────────────────────────────────────────
    ("Exeter","Devon","Devon","EX1","exeter"),
    ("Plymouth","Devon","Devon","PL1","plymouth"),
    ("Torquay","Devon","Devon","TQ1","torquay"),
    ("Paignton","Devon","Devon","TQ3","paignton"),
    ("Barnstaple","Devon","Devon","EX31","barnstaple"),
    ("Bideford","Devon","Devon","EX39","bideford"),
    ("Tiverton","Devon","Devon","EX16","tiverton"),
    ("Newton Abbot","Devon","Devon","TQ12","newton-abbot"),
    ("Exmouth","Devon","Devon","EX8","exmouth"),
    ("Sidmouth","Devon","Devon","EX10","sidmouth"),
    ("Honiton","Devon","Devon","EX14","honiton"),
    ("Crediton","Devon","Devon","EX17","crediton"),
    ("Okehampton","Devon","Devon","EX20","okehampton"),
    ("Tavistock","Devon","Devon","PL19","tavistock"),
    ("Totnes","Devon","Devon","TQ9","totnes"),
    ("Kingsbridge","Devon","Devon","TQ7","kingsbridge"),
    ("Dawlish","Devon","Devon","EX7","dawlish"),
    ("Teignmouth","Devon","Devon","TQ14","teignmouth"),
    ("Ilfracombe","Devon","Devon","EX34","ilfracombe"),
    ("Cullompton","Devon","Devon","EX15","cullompton"),
    # ── CORNWALL ──────────────────────────────────────────────────────────────
    ("Truro","Cornwall","Cornwall","TR1","truro"),
    ("Penzance","Cornwall","Cornwall","TR18","penzance"),
    ("Newquay","Cornwall","Cornwall","TR7","newquay"),
    ("Bodmin","Cornwall","Cornwall","PL31","bodmin"),
    ("Camborne","Cornwall","Cornwall","TR14","camborne"),
    ("Redruth","Cornwall","Cornwall","TR15","redruth"),
    ("Falmouth","Cornwall","Cornwall","TR11","falmouth"),
    ("St Ives Cornwall","Cornwall","Cornwall","TR26","st-ives-cornwall"),
    ("Helston","Cornwall","Cornwall","TR13","helston"),
    ("St Austell","Cornwall","Cornwall","PL25","st-austell"),
    ("Liskeard","Cornwall","Cornwall","PL14","liskeard"),
    ("Hayle","Cornwall","Cornwall","TR27","hayle"),
    ("Wadebridge","Cornwall","Cornwall","PL27","wadebridge"),
    ("Launceston","Cornwall","Cornwall","PL15","launceston"),
    ("Bude","Cornwall","Cornwall","EX23","bude"),
    ("Penryn","Cornwall","Cornwall","TR10","penryn"),
    # ── WEST MIDLANDS ─────────────────────────────────────────────────────────
    ("Birmingham","West Midlands","West Midlands","B1","birmingham"),
    ("Coventry","West Midlands","West Midlands","CV1","coventry"),
    ("Wolverhampton","West Midlands","West Midlands","WV1","wolverhampton"),
    ("Dudley","West Midlands","West Midlands","DY1","dudley"),
    ("Walsall","West Midlands","West Midlands","WS1","walsall"),
    ("Solihull","West Midlands","West Midlands","B91","solihull"),
    ("West Bromwich","West Midlands","West Midlands","B70","west-bromwich"),
    ("Smethwick","West Midlands","West Midlands","B66","smethwick"),
    ("Oldbury","West Midlands","West Midlands","B69","oldbury"),
    ("Tipton","West Midlands","West Midlands","DY4","tipton"),
    ("Wednesbury","West Midlands","West Midlands","WS10","wednesbury"),
    ("Bilston","West Midlands","West Midlands","WV14","bilston"),
    ("Willenhall","West Midlands","West Midlands","WV13","willenhall"),
    ("Bloxwich","West Midlands","West Midlands","WS3","bloxwich"),
    ("Aldridge","West Midlands","West Midlands","WS9","aldridge"),
    ("Sutton Coldfield","West Midlands","West Midlands","B72","sutton-coldfield"),
    ("Erdington","West Midlands","West Midlands","B23","erdington"),
    ("Halesowen","West Midlands","West Midlands","B63","halesowen"),
    ("Stourbridge","West Midlands","West Midlands","DY8","stourbridge"),
    ("Kingswinford","West Midlands","West Midlands","DY6","kingswinford"),
    ("Brierley Hill","West Midlands","West Midlands","DY5","brierley-hill"),
    ("Cradley Heath","West Midlands","West Midlands","B64","cradley-heath"),
    ("Harborne","West Midlands","West Midlands","B17","harborne"),
    ("Edgbaston","West Midlands","West Midlands","B15","edgbaston"),
    ("Selly Oak","West Midlands","West Midlands","B29","selly-oak"),
    ("Moseley","West Midlands","West Midlands","B13","moseley"),
    ("Kings Heath","West Midlands","West Midlands","B14","kings-heath"),
    ("Hall Green","West Midlands","West Midlands","B28","hall-green"),
    ("Acocks Green","West Midlands","West Midlands","B27","acocks-green"),
    ("Handsworth","West Midlands","West Midlands","B21","handsworth"),
    ("Great Barr","West Midlands","West Midlands","B43","great-barr"),
    ("Perry Barr","West Midlands","West Midlands","B42","perry-barr"),
    ("Kingstanding","West Midlands","West Midlands","B44","kingstanding"),
    ("Castle Bromwich","West Midlands","West Midlands","B36","castle-bromwich"),
    ("Chelmsley Wood","West Midlands","West Midlands","B37","chelmsley-wood"),
    ("Bournville","West Midlands","West Midlands","B30","bournville"),
    ("Kings Norton","West Midlands","West Midlands","B30","kings-norton"),
    ("Northfield","West Midlands","West Midlands","B31","northfield"),
    # ── WARWICKSHIRE ──────────────────────────────────────────────────────────
    ("Rugby","Warwickshire","Warwickshire","CV21","rugby"),
    ("Nuneaton","Warwickshire","Warwickshire","CV11","nuneaton"),
    ("Bedworth","Warwickshire","Warwickshire","CV12","bedworth"),
    ("Leamington Spa","Warwickshire","Warwickshire","CV31","leamington-spa"),
    ("Warwick","Warwickshire","Warwickshire","CV34","warwick"),
    ("Stratford-upon-Avon","Warwickshire","Warwickshire","CV37","stratford-upon-avon"),
    ("Kenilworth","Warwickshire","Warwickshire","CV8","kenilworth"),
    ("Atherstone","Warwickshire","Warwickshire","CV9","atherstone"),
    ("Coleshill","Warwickshire","Warwickshire","B46","coleshill"),
    ("Alcester","Warwickshire","Warwickshire","B49","alcester"),
    # ── EAST MIDLANDS ─────────────────────────────────────────────────────────
    ("Leicester","Leicestershire","Leicestershire","LE1","leicester"),
    ("Nottingham","Nottinghamshire","Nottinghamshire","NG1","nottingham"),
    ("Derby","Derbyshire","Derbyshire","DE1","derby"),
    ("Lincoln","Lincolnshire","Lincolnshire","LN1","lincoln"),
    ("Mansfield","Nottinghamshire","Nottinghamshire","NG18","mansfield"),
    ("Chesterfield","Derbyshire","Derbyshire","S40","chesterfield"),
    ("Loughborough","Leicestershire","Leicestershire","LE11","loughborough"),
    ("Market Harborough","Leicestershire","Leicestershire","LE16","market-harborough"),
    ("Hinckley","Leicestershire","Leicestershire","LE10","hinckley"),
    ("Melton Mowbray","Leicestershire","Leicestershire","LE13","melton-mowbray"),
    ("Oakham","Rutland","Rutland","LE15","oakham"),
    ("Stamford","Lincolnshire","Lincolnshire","PE9","stamford"),
    ("Grantham","Lincolnshire","Lincolnshire","NG31","grantham"),
    ("Newark-on-Trent","Nottinghamshire","Nottinghamshire","NG24","newark-on-trent"),
    ("Worksop","Nottinghamshire","Nottinghamshire","S80","worksop"),
    ("Retford","Nottinghamshire","Nottinghamshire","DN22","retford"),
    ("Sutton-in-Ashfield","Nottinghamshire","Nottinghamshire","NG17","sutton-in-ashfield"),
    ("Hucknall","Nottinghamshire","Nottinghamshire","NG15","hucknall"),
    ("Arnold","Nottinghamshire","Nottinghamshire","NG5","arnold"),
    ("West Bridgford","Nottinghamshire","Nottinghamshire","NG2","west-bridgford"),
    ("Beeston","Nottinghamshire","Nottinghamshire","NG9","beeston"),
    ("Long Eaton","Derbyshire","Derbyshire","NG10","long-eaton"),
    ("Ilkeston","Derbyshire","Derbyshire","DE7","ilkeston"),
    ("Ripley Derbyshire","Derbyshire","Derbyshire","DE5","ripley-derbyshire"),
    ("Alfreton","Derbyshire","Derbyshire","DE55","alfreton"),
    ("Swadlincote","Derbyshire","Derbyshire","DE11","swadlincote"),
    ("Buxton","Derbyshire","Derbyshire","SK17","buxton"),
    ("Matlock","Derbyshire","Derbyshire","DE4","matlock"),
    ("Ashbourne","Derbyshire","Derbyshire","DE6","ashbourne"),
    ("Glossop","Derbyshire","Derbyshire","SK13","glossop"),
    ("Dronfield","Derbyshire","Derbyshire","S18","dronfield"),
    ("Grimsby","Lincolnshire","Lincolnshire","DN31","grimsby"),
    ("Scunthorpe","Lincolnshire","Lincolnshire","DN15","scunthorpe"),
    ("Cleethorpes","Lincolnshire","Lincolnshire","DN35","cleethorpes"),
    ("Skegness","Lincolnshire","Lincolnshire","PE25","skegness"),
    ("Spalding","Lincolnshire","Lincolnshire","PE11","spalding"),
    ("Boston","Lincolnshire","Lincolnshire","PE21","boston"),
    ("Sleaford","Lincolnshire","Lincolnshire","NG34","sleaford"),
    ("Louth","Lincolnshire","Lincolnshire","LN11","louth"),
    ("Gainsborough","Lincolnshire","Lincolnshire","DN21","gainsborough"),
    ("Coalville","Leicestershire","Leicestershire","LE67","coalville"),
    ("Ashby-de-la-Zouch","Leicestershire","Leicestershire","LE65","ashby-de-la-zouch"),
    ("Oadby","Leicestershire","Leicestershire","LE2","oadby"),
    ("Wigston","Leicestershire","Leicestershire","LE18","wigston"),
    ("Lutterworth","Leicestershire","Leicestershire","LE17","lutterworth"),
    # ── STAFFORDSHIRE ─────────────────────────────────────────────────────────
    ("Stoke-on-Trent","Staffordshire","Staffordshire","ST1","stoke-on-trent"),
    ("Stafford","Staffordshire","Staffordshire","ST16","stafford"),
    ("Tamworth","Staffordshire","Staffordshire","B77","tamworth"),
    ("Lichfield","Staffordshire","Staffordshire","WS13","lichfield"),
    ("Burton-on-Trent","Staffordshire","Staffordshire","DE14","burton-on-trent"),
    ("Cannock","Staffordshire","Staffordshire","WS11","cannock"),
    ("Rugeley","Staffordshire","Staffordshire","WS15","rugeley"),
    ("Newcastle-under-Lyme","Staffordshire","Staffordshire","ST5","newcastle-under-lyme"),
    ("Leek","Staffordshire","Staffordshire","ST13","leek"),
    ("Uttoxeter","Staffordshire","Staffordshire","ST14","uttoxeter"),
    ("Kidsgrove","Staffordshire","Staffordshire","ST7","kidsgrove"),
    # ── SHROPSHIRE / WORCESTERSHIRE / HEREFORDSHIRE ───────────────────────────
    ("Shrewsbury","Shropshire","Shropshire","SY1","shrewsbury"),
    ("Telford","Shropshire","Shropshire","TF1","telford"),
    ("Oswestry","Shropshire","Shropshire","SY11","oswestry"),
    ("Bridgnorth","Shropshire","Shropshire","WV16","bridgnorth"),
    ("Ludlow","Shropshire","Shropshire","SY8","ludlow"),
    ("Shifnal","Shropshire","Shropshire","TF11","shifnal"),
    ("Worcester","Worcestershire","Worcestershire","WR1","worcester"),
    ("Redditch","Worcestershire","Worcestershire","B97","redditch"),
    ("Kidderminster","Worcestershire","Worcestershire","DY10","kidderminster"),
    ("Evesham","Worcestershire","Worcestershire","WR11","evesham"),
    ("Malvern","Worcestershire","Worcestershire","WR14","malvern"),
    ("Droitwich Spa","Worcestershire","Worcestershire","WR9","droitwich-spa"),
    ("Bromsgrove","Worcestershire","Worcestershire","B61","bromsgrove"),
    ("Stourport-on-Severn","Worcestershire","Worcestershire","DY13","stourport-on-severn"),
    ("Hereford","Herefordshire","Herefordshire","HR1","hereford"),
    ("Leominster","Herefordshire","Herefordshire","HR6","leominster"),
    ("Ross-on-Wye","Herefordshire","Herefordshire","HR9","ross-on-wye"),
    ("Ledbury","Herefordshire","Herefordshire","HR8","ledbury"),
    # ── GREATER MANCHESTER ────────────────────────────────────────────────────
    ("Manchester","Greater Manchester","Greater Manchester","M1","manchester"),
    ("Salford","Greater Manchester","Greater Manchester","M5","salford"),
    ("Bolton","Greater Manchester","Greater Manchester","BL1","bolton"),
    ("Oldham","Greater Manchester","Greater Manchester","OL1","oldham"),
    ("Rochdale","Greater Manchester","Greater Manchester","OL16","rochdale"),
    ("Stockport","Greater Manchester","Greater Manchester","SK1","stockport"),
    ("Wigan","Greater Manchester","Greater Manchester","WN1","wigan"),
    ("Bury","Greater Manchester","Greater Manchester","BL9","bury"),
    ("Trafford","Greater Manchester","Greater Manchester","WA14","trafford"),
    ("Eccles","Greater Manchester","Greater Manchester","M30","eccles"),
    ("Sale","Greater Manchester","Greater Manchester","M33","sale"),
    ("Altrincham","Greater Manchester","Greater Manchester","WA14","altrincham"),
    ("Cheadle","Greater Manchester","Greater Manchester","SK8","cheadle"),
    ("Hazel Grove","Greater Manchester","Greater Manchester","SK7","hazel-grove"),
    ("Wilmslow","Cheshire","Cheshire","SK9","wilmslow"),
    ("Didsbury","Greater Manchester","Greater Manchester","M20","didsbury"),
    ("Chorlton","Greater Manchester","Greater Manchester","M21","chorlton"),
    ("Wythenshawe","Greater Manchester","Greater Manchester","M22","wythenshawe"),
    ("Prestwich","Greater Manchester","Greater Manchester","M25","prestwich"),
    ("Whitefield","Greater Manchester","Greater Manchester","M45","whitefield"),
    ("Radcliffe","Greater Manchester","Greater Manchester","M26","radcliffe"),
    ("Farnworth","Greater Manchester","Greater Manchester","BL4","farnworth"),
    ("Horwich","Greater Manchester","Greater Manchester","BL6","horwich"),
    ("Westhoughton","Greater Manchester","Greater Manchester","BL5","westhoughton"),
    ("Atherton","Greater Manchester","Greater Manchester","M46","atherton"),
    ("Tyldesley","Greater Manchester","Greater Manchester","M29","tyldesley"),
    ("Leigh","Greater Manchester","Greater Manchester","WN7","leigh"),
    ("Ashton-under-Lyne","Greater Manchester","Greater Manchester","OL6","ashton-under-lyne"),
    ("Denton","Greater Manchester","Greater Manchester","M34","denton"),
    ("Hyde","Greater Manchester","Greater Manchester","SK14","hyde"),
    ("Stalybridge","Greater Manchester","Greater Manchester","SK15","stalybridge"),
    ("Failsworth","Greater Manchester","Greater Manchester","M35","failsworth"),
    ("Royton","Greater Manchester","Greater Manchester","OL2","royton"),
    ("Chadderton","Greater Manchester","Greater Manchester","OL9","chadderton"),
    ("Heywood","Greater Manchester","Greater Manchester","OL10","heywood"),
    ("Middleton","Greater Manchester","Greater Manchester","M24","middleton"),
    ("Ramsbottom","Greater Manchester","Greater Manchester","BL0","ramsbottom"),
    ("Reddish","Greater Manchester","Greater Manchester","SK5","reddish"),
    ("Heaton Moor","Greater Manchester","Greater Manchester","SK4","heaton-moor"),
    ("Worsley","Greater Manchester","Greater Manchester","M28","worsley"),
    ("Walkden","Greater Manchester","Greater Manchester","M28","walkden"),
    ("Swinton","Greater Manchester","Greater Manchester","M27","swinton"),
    ("Shaw","Greater Manchester","Greater Manchester","OL2","shaw"),
    ("Mossley","Greater Manchester","Greater Manchester","OL5","mossley"),
    ("Littleborough","Greater Manchester","Greater Manchester","OL15","littleborough"),
    ("Milnrow","Greater Manchester","Greater Manchester","OL16","milnrow"),
    ("Tottington","Greater Manchester","Greater Manchester","BL8","tottington"),
    ("Standish","Greater Manchester","Greater Manchester","WN6","standish"),
    ("Shevington","Greater Manchester","Greater Manchester","WN6","shevington"),
    ("Orrell","Greater Manchester","Greater Manchester","WN5","orrell"),
    # ── MERSEYSIDE ────────────────────────────────────────────────────────────
    ("Liverpool","Merseyside","Merseyside","L1","liverpool"),
    ("Birkenhead","Merseyside","Merseyside","CH41","birkenhead"),
    ("St Helens","Merseyside","Merseyside","WA10","st-helens"),
    ("Southport","Merseyside","Merseyside","PR8","southport"),
    ("Bootle","Merseyside","Merseyside","L20","bootle"),
    ("Wallasey","Merseyside","Merseyside","CH44","wallasey"),
    ("Kirkby","Merseyside","Merseyside","L32","kirkby"),
    ("Huyton","Merseyside","Merseyside","L36","huyton"),
    ("Prescot","Merseyside","Merseyside","L34","prescot"),
    ("Formby","Merseyside","Merseyside","L37","formby"),
    ("Crosby","Merseyside","Merseyside","L23","crosby"),
    ("Heswall","Merseyside","Merseyside","CH60","heswall"),
    ("West Kirby","Merseyside","Merseyside","CH48","west-kirby"),
    ("Hoylake","Merseyside","Merseyside","CH47","hoylake"),
    ("Bebington","Merseyside","Merseyside","CH63","bebington"),
    ("Bromborough","Merseyside","Merseyside","CH62","bromborough"),
    ("Toxteth","Merseyside","Merseyside","L8","toxteth"),
    ("Wavertree","Merseyside","Merseyside","L15","wavertree"),
    ("West Derby","Merseyside","Merseyside","L12","west-derby"),
    ("Fazakerley","Merseyside","Merseyside","L10","fazakerley"),
    ("Allerton","Merseyside","Merseyside","L18","allerton"),
    ("Woolton","Merseyside","Merseyside","L25","woolton"),
    ("Garston","Merseyside","Merseyside","L19","garston"),
    ("Ormskirk","Lancashire","Lancashire","L39","ormskirk"),
    ("Skelmersdale","Lancashire","Lancashire","WN8","skelmersdale"),
    ("Newton-le-Willows","Merseyside","Merseyside","WA12","newton-le-willows"),
    ("Haydock","Merseyside","Merseyside","WA11","haydock"),
    ("Rainford","Merseyside","Merseyside","WA11","rainford"),
    ("Billinge","Merseyside","Merseyside","WN5","billinge"),
    # ── CHESHIRE ──────────────────────────────────────────────────────────────
    ("Warrington","Cheshire","Cheshire","WA1","warrington"),
    ("Chester","Cheshire","Cheshire","CH1","chester"),
    ("Crewe","Cheshire","Cheshire","CW1","crewe"),
    ("Northwich","Cheshire","Cheshire","CW9","northwich"),
    ("Congleton","Cheshire","Cheshire","CW12","congleton"),
    ("Winsford","Cheshire","Cheshire","CW7","winsford"),
    ("Macclesfield","Cheshire","Cheshire","SK10","macclesfield"),
    ("Knutsford","Cheshire","Cheshire","WA16","knutsford"),
    ("Nantwich","Cheshire","Cheshire","CW5","nantwich"),
    ("Sandbach","Cheshire","Cheshire","CW11","sandbach"),
    ("Runcorn","Cheshire","Cheshire","WA7","runcorn"),
    ("Widnes","Cheshire","Cheshire","WA8","widnes"),
    ("Ellesmere Port","Cheshire","Cheshire","CH65","ellesmere-port"),
    # ── LANCASHIRE ────────────────────────────────────────────────────────────
    ("Preston","Lancashire","Lancashire","PR1","preston"),
    ("Blackpool","Lancashire","Lancashire","FY1","blackpool"),
    ("Blackburn","Lancashire","Lancashire","BB1","blackburn"),
    ("Burnley","Lancashire","Lancashire","BB11","burnley"),
    ("Lancaster","Lancashire","Lancashire","LA1","lancaster"),
    ("Accrington","Lancashire","Lancashire","BB5","accrington"),
    ("Nelson","Lancashire","Lancashire","BB9","nelson"),
    ("Clitheroe","Lancashire","Lancashire","BB7","clitheroe"),
    ("Rawtenstall","Lancashire","Lancashire","BB4","rawtenstall"),
    ("Colne","Lancashire","Lancashire","BB8","colne"),
    ("Morecambe","Lancashire","Lancashire","LA4","morecambe"),
    ("Fleetwood","Lancashire","Lancashire","FY7","fleetwood"),
    ("Cleveleys","Lancashire","Lancashire","FY5","cleveleys"),
    ("Lytham St Annes","Lancashire","Lancashire","FY8","lytham-st-annes"),
    ("Leyland","Lancashire","Lancashire","PR25","leyland"),
    ("Chorley","Lancashire","Lancashire","PR7","chorley"),
    ("Bamber Bridge","Lancashire","Lancashire","PR5","bamber-bridge"),
    ("Poulton-le-Fylde","Lancashire","Lancashire","FY6","poulton-le-fylde"),
    ("Garstang","Lancashire","Lancashire","PR3","garstang"),
    ("Longridge","Lancashire","Lancashire","PR3","longridge"),
    ("Oswaldtwistle","Lancashire","Lancashire","BB5","oswaldtwistle"),
    ("Great Harwood","Lancashire","Lancashire","BB6","great-harwood"),
    ("Padiham","Lancashire","Lancashire","BB12","padiham"),
    ("Brierfield","Lancashire","Lancashire","BB9","brierfield"),
    ("Barnoldswick","Lancashire","Lancashire","BB18","barnoldswick"),
    ("Haslingden","Lancashire","Lancashire","BB4","haslingden"),
    ("Bacup","Lancashire","Lancashire","OL13","bacup"),
    ("Penwortham","Lancashire","Lancashire","PR1","penwortham"),
    ("Kirkham","Lancashire","Lancashire","PR4","kirkham"),
    # ── YORKSHIRE ─────────────────────────────────────────────────────────────
    ("Leeds","West Yorkshire","West Yorkshire","LS1","leeds"),
    ("Sheffield","South Yorkshire","South Yorkshire","S1","sheffield"),
    ("Bradford","West Yorkshire","West Yorkshire","BD1","bradford"),
    ("Hull","East Yorkshire","East Yorkshire","HU1","hull"),
    ("Huddersfield","West Yorkshire","West Yorkshire","HD1","huddersfield"),
    ("Halifax","West Yorkshire","West Yorkshire","HX1","halifax"),
    ("Wakefield","West Yorkshire","West Yorkshire","WF1","wakefield"),
    ("Barnsley","South Yorkshire","South Yorkshire","S70","barnsley"),
    ("Rotherham","South Yorkshire","South Yorkshire","S60","rotherham"),
    ("Doncaster","South Yorkshire","South Yorkshire","DN1","doncaster"),
    ("York","North Yorkshire","North Yorkshire","YO1","york"),
    ("Harrogate","North Yorkshire","North Yorkshire","HG1","harrogate"),
    ("Scarborough","North Yorkshire","North Yorkshire","YO11","scarborough"),
    ("Middlesbrough","Teesside","Teesside","TS1","middlesbrough"),
    ("Darlington","County Durham","County Durham","DL1","darlington"),
    ("Keighley","West Yorkshire","West Yorkshire","BD21","keighley"),
    ("Dewsbury","West Yorkshire","West Yorkshire","WF12","dewsbury"),
    ("Pontefract","West Yorkshire","West Yorkshire","WF8","pontefract"),
    ("Castleford","West Yorkshire","West Yorkshire","WF10","castleford"),
    ("Ossett","West Yorkshire","West Yorkshire","WF5","ossett"),
    ("Batley","West Yorkshire","West Yorkshire","WF17","batley"),
    ("Morley","West Yorkshire","West Yorkshire","LS27","morley"),
    ("Pudsey","West Yorkshire","West Yorkshire","LS28","pudsey"),
    ("Horsforth","West Yorkshire","West Yorkshire","LS18","horsforth"),
    ("Guiseley","West Yorkshire","West Yorkshire","LS20","guiseley"),
    ("Otley","West Yorkshire","West Yorkshire","LS21","otley"),
    ("Ilkley","West Yorkshire","West Yorkshire","LS29","ilkley"),
    ("Shipley","West Yorkshire","West Yorkshire","BD18","shipley"),
    ("Bingley","West Yorkshire","West Yorkshire","BD16","bingley"),
    ("Baildon","West Yorkshire","West Yorkshire","BD17","baildon"),
    ("Cleckheaton","West Yorkshire","West Yorkshire","BD19","cleckheaton"),
    ("Heckmondwike","West Yorkshire","West Yorkshire","WF16","heckmondwike"),
    ("Mirfield","West Yorkshire","West Yorkshire","WF14","mirfield"),
    ("Sowerby Bridge","West Yorkshire","West Yorkshire","HX6","sowerby-bridge"),
    ("Brighouse","West Yorkshire","West Yorkshire","HD6","brighouse"),
    ("Hebden Bridge","West Yorkshire","West Yorkshire","HX7","hebden-bridge"),
    ("Todmorden","West Yorkshire","West Yorkshire","OL14","todmorden"),
    ("Holmfirth","West Yorkshire","West Yorkshire","HD9","holmfirth"),
    ("Wetherby","West Yorkshire","West Yorkshire","LS22","wetherby"),
    ("Normanton","West Yorkshire","West Yorkshire","WF6","normanton"),
    ("Featherstone","West Yorkshire","West Yorkshire","WF7","featherstone"),
    ("Penistone","South Yorkshire","South Yorkshire","S36","penistone"),
    ("Wombwell","South Yorkshire","South Yorkshire","S73","wombwell"),
    ("Mexborough","South Yorkshire","South Yorkshire","S64","mexborough"),
    ("Conisbrough","South Yorkshire","South Yorkshire","DN12","conisbrough"),
    ("Maltby","South Yorkshire","South Yorkshire","S66","maltby"),
    ("Chapeltown","South Yorkshire","South Yorkshire","S35","chapeltown"),
    ("Stocksbridge","South Yorkshire","South Yorkshire","S36","stocksbridge"),
    ("Thorne","South Yorkshire","South Yorkshire","DN8","thorne"),
    ("Selby","North Yorkshire","North Yorkshire","YO8","selby"),
    ("Goole","East Yorkshire","East Yorkshire","DN14","goole"),
    ("Beverley","East Yorkshire","East Yorkshire","HU17","beverley"),
    ("Bridlington","East Yorkshire","East Yorkshire","YO15","bridlington"),
    ("Driffield","East Yorkshire","East Yorkshire","YO25","driffield"),
    ("Hessle","East Yorkshire","East Yorkshire","HU13","hessle"),
    ("Cottingham","East Yorkshire","East Yorkshire","HU16","cottingham"),
    ("Brough","East Yorkshire","East Yorkshire","HU15","brough"),
    ("Thirsk","North Yorkshire","North Yorkshire","YO7","thirsk"),
    ("Northallerton","North Yorkshire","North Yorkshire","DL6","northallerton"),
    ("Ripon","North Yorkshire","North Yorkshire","HG4","ripon"),
    ("Skipton","North Yorkshire","North Yorkshire","BD23","skipton"),
    ("Knaresborough","North Yorkshire","North Yorkshire","HG5","knaresborough"),
    ("Whitby","North Yorkshire","North Yorkshire","YO21","whitby"),
    ("Malton","North Yorkshire","North Yorkshire","YO17","malton"),
    ("Pickering","North Yorkshire","North Yorkshire","YO18","pickering"),
    ("Filey","North Yorkshire","North Yorkshire","YO14","filey"),
    ("Guisborough","North Yorkshire","North Yorkshire","TS14","guisborough"),
    ("Redcar","Teesside","Teesside","TS10","redcar"),
    ("Saltburn-by-the-Sea","Teesside","Teesside","TS12","saltburn-by-the-sea"),
    ("Thornaby-on-Tees","Teesside","Teesside","TS17","thornaby-on-tees"),
    ("Yarm","Teesside","Teesside","TS15","yarm"),
    ("Billingham","Teesside","Teesside","TS23","billingham"),
    ("Stockton-on-Tees","Teesside","Teesside","TS18","stockton-on-tees"),
    ("Hartlepool","County Durham","County Durham","TS24","hartlepool"),
    ("Settle","North Yorkshire","North Yorkshire","BD24","settle"),
    ("Grassington","North Yorkshire","North Yorkshire","BD23","grassington"),
    ("Golcar","West Yorkshire","West Yorkshire","HD7","golcar"),
    ("Marsden","West Yorkshire","West Yorkshire","HD7","marsden"),
    ("Kirkburton","West Yorkshire","West Yorkshire","HD8","kirkburton"),
    ("Denby Dale","West Yorkshire","West Yorkshire","HD8","denby-dale"),
    ("Stokesley","North Yorkshire","North Yorkshire","TS9","stokesley"),
    # ── NORTH EAST ────────────────────────────────────────────────────────────
    ("Newcastle","Tyne and Wear","Tyne and Wear","NE1","newcastle"),
    ("Sunderland","Tyne and Wear","Tyne and Wear","SR1","sunderland"),
    ("Gateshead","Tyne and Wear","Tyne and Wear","NE8","gateshead"),
    ("Durham","County Durham","County Durham","DH1","durham"),
    ("South Shields","Tyne and Wear","Tyne and Wear","NE33","south-shields"),
    ("North Shields","Tyne and Wear","Tyne and Wear","NE29","north-shields"),
    ("Tynemouth","Tyne and Wear","Tyne and Wear","NE30","tynemouth"),
    ("Whitley Bay","Tyne and Wear","Tyne and Wear","NE26","whitley-bay"),
    ("Cramlington","Northumberland","Northumberland","NE23","cramlington"),
    ("Blyth","Northumberland","Northumberland","NE24","blyth"),
    ("Ashington","Northumberland","Northumberland","NE63","ashington"),
    ("Morpeth","Northumberland","Northumberland","NE61","morpeth"),
    ("Hexham","Northumberland","Northumberland","NE46","hexham"),
    ("Alnwick","Northumberland","Northumberland","NE66","alnwick"),
    ("Berwick-upon-Tweed","Northumberland","Northumberland","TD15","berwick-upon-tweed"),
    ("Chester-le-Street","County Durham","County Durham","DH3","chester-le-street"),
    ("Washington","Tyne and Wear","Tyne and Wear","NE37","washington"),
    ("Houghton-le-Spring","Tyne and Wear","Tyne and Wear","DH4","houghton-le-spring"),
    ("Seaham","County Durham","County Durham","SR7","seaham"),
    ("Peterlee","County Durham","County Durham","SR8","peterlee"),
    ("Consett","County Durham","County Durham","DH8","consett"),
    ("Stanley","County Durham","County Durham","DH9","stanley"),
    ("Bishop Auckland","County Durham","County Durham","DL14","bishop-auckland"),
    ("Spennymoor","County Durham","County Durham","DL16","spennymoor"),
    ("Newton Aycliffe","County Durham","County Durham","DL5","newton-aycliffe"),
    ("Jarrow","Tyne and Wear","Tyne and Wear","NE32","jarrow"),
    ("Hebburn","Tyne and Wear","Tyne and Wear","NE31","hebburn"),
    ("Blaydon","Tyne and Wear","Tyne and Wear","NE21","blaydon"),
    ("Ponteland","Northumberland","Northumberland","NE20","ponteland"),
    ("Prudhoe","Northumberland","Northumberland","NE42","prudhoe"),
    # ── CUMBRIA ───────────────────────────────────────────────────────────────
    ("Carlisle","Cumbria","Cumbria","CA1","carlisle"),
    ("Barrow-in-Furness","Cumbria","Cumbria","LA14","barrow-in-furness"),
    ("Kendal","Cumbria","Cumbria","LA9","kendal"),
    ("Penrith","Cumbria","Cumbria","CA11","penrith"),
    ("Workington","Cumbria","Cumbria","CA14","workington"),
    ("Whitehaven","Cumbria","Cumbria","CA28","whitehaven"),
    ("Keswick","Cumbria","Cumbria","CA12","keswick"),
    ("Windermere","Cumbria","Cumbria","LA23","windermere"),
    ("Ulverston","Cumbria","Cumbria","LA12","ulverston"),
    ("Cockermouth","Cumbria","Cumbria","CA13","cockermouth"),
    ("Dalton-in-Furness","Cumbria","Cumbria","LA15","dalton-in-furness"),
    ("Grange-over-Sands","Cumbria","Cumbria","LA11","grange-over-sands"),
    # ── NORFOLK ───────────────────────────────────────────────────────────────
    ("Norwich","Norfolk","Norfolk","NR1","norwich"),
    ("Great Yarmouth","Norfolk","Norfolk","NR30","great-yarmouth"),
    ("Kings Lynn","Norfolk","Norfolk","PE30","kings-lynn"),
    ("Thetford","Norfolk","Norfolk","IP24","thetford"),
    ("Dereham","Norfolk","Norfolk","NR19","dereham"),
    ("North Walsham","Norfolk","Norfolk","NR28","north-walsham"),
    ("Cromer","Norfolk","Norfolk","NR27","cromer"),
    ("Sheringham","Norfolk","Norfolk","NR26","sheringham"),
    ("Attleborough","Norfolk","Norfolk","NR17","attleborough"),
    ("Wymondham","Norfolk","Norfolk","NR18","wymondham"),
    ("Fakenham","Norfolk","Norfolk","NR21","fakenham"),
    # ── SUFFOLK ───────────────────────────────────────────────────────────────
    ("Ipswich","Suffolk","Suffolk","IP1","ipswich"),
    ("Bury St Edmunds","Suffolk","Suffolk","IP33","bury-st-edmunds"),
    ("Lowestoft","Suffolk","Suffolk","NR32","lowestoft"),
    ("Newmarket","Suffolk","Suffolk","CB8","newmarket"),
    ("Sudbury","Suffolk","Suffolk","CO10","sudbury"),
    ("Haverhill","Suffolk","Suffolk","CB9","haverhill"),
    ("Felixstowe","Suffolk","Suffolk","IP11","felixstowe"),
    ("Woodbridge","Suffolk","Suffolk","IP12","woodbridge"),
    ("Stowmarket","Suffolk","Suffolk","IP14","stowmarket"),
    ("Beccles","Suffolk","Suffolk","NR34","beccles"),
    ("Framlingham","Suffolk","Suffolk","IP13","framlingham"),
    # ── SCOTLAND ──────────────────────────────────────────────────────────────
    ("Glasgow","Scotland","Scotland","G1","glasgow"),
    ("Edinburgh","Scotland","Scotland","EH1","edinburgh"),
    ("Aberdeen","Scotland","Scotland","AB10","aberdeen"),
    ("Dundee","Scotland","Scotland","DD1","dundee"),
    ("Inverness","Scotland","Scotland","IV1","inverness"),
    ("Stirling","Scotland","Scotland","FK8","stirling"),
    ("Perth","Scotland","Scotland","PH1","perth"),
    ("Paisley","Scotland","Scotland","PA1","paisley"),
    ("Kilmarnock","Scotland","Scotland","KA1","kilmarnock"),
    ("Hamilton","Scotland","Scotland","ML3","hamilton"),
    ("Ayr","Scotland","Scotland","KA7","ayr"),
    ("Falkirk","Scotland","Scotland","FK1","falkirk"),
    ("Dumfries","Scotland","Scotland","DG1","dumfries"),
    ("Motherwell","Scotland","Scotland","ML1","motherwell"),
    ("Coatbridge","Scotland","Scotland","ML5","coatbridge"),
    ("Airdrie","Scotland","Scotland","ML6","airdrie"),
    ("Cumbernauld","Scotland","Scotland","G67","cumbernauld"),
    ("East Kilbride","Scotland","Scotland","G74","east-kilbride"),
    ("Livingston","Scotland","Scotland","EH54","livingston"),
    ("Dunfermline","Scotland","Scotland","KY11","dunfermline"),
    ("Kirkcaldy","Scotland","Scotland","KY1","kirkcaldy"),
    ("Glenrothes","Scotland","Scotland","KY7","glenrothes"),
    ("Greenock","Scotland","Scotland","PA15","greenock"),
    ("Dumbarton","Scotland","Scotland","G82","dumbarton"),
    ("Clydebank","Scotland","Scotland","G81","clydebank"),
    ("Bishopbriggs","Scotland","Scotland","G64","bishopbriggs"),
    ("Bearsden","Scotland","Scotland","G61","bearsden"),
    ("Rutherglen","Scotland","Scotland","G73","rutherglen"),
    ("Newton Mearns","Scotland","Scotland","G77","newton-mearns"),
    ("Barrhead","Scotland","Scotland","G78","barrhead"),
    ("Renfrew","Scotland","Scotland","PA4","renfrew"),
    ("Johnstone","Scotland","Scotland","PA5","johnstone"),
    ("Irvine","Scotland","Scotland","KA12","irvine"),
    ("Kilwinning","Scotland","Scotland","KA13","kilwinning"),
    ("Saltcoats","Scotland","Scotland","KA21","saltcoats"),
    ("Ardrossan","Scotland","Scotland","KA22","ardrossan"),
    ("Largs","Scotland","Scotland","KA30","largs"),
    ("Troon","Scotland","Scotland","KA10","troon"),
    ("Prestwick","Scotland","Scotland","KA9","prestwick"),
    ("Larkhall","Scotland","Scotland","ML9","larkhall"),
    ("Wishaw","Scotland","Scotland","ML2","wishaw"),
    ("Bellshill","Scotland","Scotland","ML4","bellshill"),
    ("Carluke","Scotland","Scotland","ML8","carluke"),
    ("Bathgate","Scotland","Scotland","EH48","bathgate"),
    ("Linlithgow","Scotland","Scotland","EH49","linlithgow"),
    ("Grangemouth","Scotland","Scotland","FK3","grangemouth"),
    ("Alloa","Scotland","Scotland","FK10","alloa"),
    ("Bo'ness","Scotland","Scotland","FK10","bo-ness"),
    ("Crieff","Scotland","Scotland","PH7","crieff"),
    ("Pitlochry","Scotland","Scotland","PH16","pitlochry"),
    ("Blairgowrie","Scotland","Scotland","PH10","blairgowrie"),
    ("Arbroath","Scotland","Scotland","DD11","arbroath"),
    ("Montrose","Scotland","Scotland","DD10","montrose"),
    ("Carnoustie","Scotland","Scotland","DD7","carnoustie"),
    ("St Andrews","Scotland","Scotland","KY16","st-andrews"),
    ("Cupar","Scotland","Scotland","KY15","cupar"),
    ("Leven","Scotland","Scotland","KY8","leven"),
    ("Cowdenbeath","Scotland","Scotland","KY4","cowdenbeath"),
    ("Kinross","Scotland","Scotland","KY13","kinross"),
    ("Inverkeithing","Scotland","Scotland","KY11","inverkeithing"),
    ("Rosyth","Scotland","Scotland","KY11","rosyth"),
    ("Musselburgh","Scotland","Scotland","EH21","musselburgh"),
    ("Haddington","Scotland","Scotland","EH41","haddington"),
    ("Dunbar","Scotland","Scotland","EH42","dunbar"),
    ("North Berwick","Scotland","Scotland","EH39","north-berwick"),
    ("Dalkeith","Scotland","Scotland","EH22","dalkeith"),
    ("Bonnyrigg","Scotland","Scotland","EH19","bonnyrigg"),
    ("Penicuik","Scotland","Scotland","EH26","penicuik"),
    ("Galashiels","Scotland","Scotland","TD1","galashiels"),
    ("Hawick","Scotland","Scotland","TD9","hawick"),
    ("Kelso","Scotland","Scotland","TD5","kelso"),
    ("Elgin","Scotland","Scotland","IV30","elgin"),
    ("Forres","Scotland","Scotland","IV36","forres"),
    ("Fraserburgh","Scotland","Scotland","AB43","fraserburgh"),
    ("Peterhead","Scotland","Scotland","AB42","peterhead"),
    ("Stonehaven","Scotland","Scotland","AB39","stonehaven"),
    ("Fort William","Scotland","Scotland","PH33","fort-william"),
    ("Oban","Scotland","Scotland","PA34","oban"),
    ("Stornoway","Scotland","Scotland","HS1","stornoway"),
    ("Nairn","Scotland","Scotland","IV12","nairn"),
    ("Huntly","Scotland","Scotland","AB54","huntly"),
    ("Keith","Scotland","Scotland","AB55","keith"),
    ("Forfar","Scotland","Scotland","DD8","forfar"),
    ("Brechin","Scotland","Scotland","DD9","brechin"),
    ("Port Glasgow","Scotland","Scotland","PA14","port-glasgow"),
    ("Loanhead","Scotland","Scotland","EH20","loanhead"),
    ("Prestonpans","Scotland","Scotland","EH32","prestonpans"),
    ("Tranent","Scotland","Scotland","EH33","tranent"),
    ("Milngavie","Scotland","Scotland","G62","milngavie"),
    ("Cambuslang","Scotland","Scotland","G72","cambuslang"),
    ("Uddingston","Scotland","Scotland","G71","uddingston"),
    ("Blantyre","Scotland","Scotland","G72","blantyre"),
    ("Giffnock","Scotland","Scotland","G46","giffnock"),
    ("Kirkintilloch","Scotland","Scotland","G66","kirkintilloch"),
    ("Lenzie","Scotland","Scotland","G66","lenzie"),
    ("Alexandria","Scotland","Scotland","G83","alexandria"),
    ("Helensburgh","Scotland","Scotland","G84","helensburgh"),
    ("Beith","Scotland","Scotland","KA15","beith"),
    ("Dalry","Scotland","Scotland","KA24","dalry"),
    ("Stewarton","Scotland","Scotland","KA3","stewarton"),
    ("Galston","Scotland","Scotland","KA4","galston"),
    ("Cumnock","Scotland","Scotland","KA18","cumnock"),
    ("Girvan","Scotland","Scotland","KA26","girvan"),
    ("Maybole","Scotland","Scotland","KA19","maybole"),
    ("Shotts","Scotland","Scotland","ML7","shotts"),
    ("Whitburn","Scotland","Scotland","EH47","whitburn"),
    ("Fauldhouse","Scotland","Scotland","EH47","fauldhouse"),
    ("West Calder","Scotland","Scotland","EH55","west-calder"),
    ("Balerno","Scotland","Scotland","EH14","balerno"),
    ("Currie","Scotland","Scotland","EH14","currie"),
    ("Colinton","Scotland","Scotland","EH13","colinton"),
    ("Morningside","Scotland","Scotland","EH10","morningside"),
    ("Newington Edinburgh","Scotland","Scotland","EH9","newington-edinburgh"),
    ("Gorgie","Scotland","Scotland","EH11","gorgie"),
    ("Corstorphine","Scotland","Scotland","EH12","corstorphine"),
    ("Stockbridge Edinburgh","Scotland","Scotland","EH4","stockbridge-edinburgh"),
    ("Leith","Scotland","Scotland","EH6","leith"),
    ("Portobello","Scotland","Scotland","EH15","portobello"),
    ("Craigmillar","Scotland","Scotland","EH16","craigmillar"),
    ("Larbert","Scotland","Scotland","FK5","larbert"),
    ("Denny","Scotland","Scotland","FK6","denny"),
    ("Kilsyth","Scotland","Scotland","G65","kilsyth"),
    # ── WALES ─────────────────────────────────────────────────────────────────
    ("Cardiff","Wales","Wales","CF10","cardiff"),
    ("Swansea","Wales","Wales","SA1","swansea"),
    ("Newport","Wales","Wales","NP20","newport"),
    ("Wrexham","Wales","Wales","LL11","wrexham"),
    ("Bridgend","Wales","Wales","CF31","bridgend"),
    ("Merthyr Tydfil","Wales","Wales","CF47","merthyr-tydfil"),
    ("Llanelli","Wales","Wales","SA14","llanelli"),
    ("Neath","Wales","Wales","SA11","neath"),
    ("Pontypridd","Wales","Wales","CF37","pontypridd"),
    ("Rhondda","Wales","Wales","CF40","rhondda"),
    ("Barry","Wales","Wales","CF62","barry"),
    ("Penarth","Wales","Wales","CF64","penarth"),
    ("Caerphilly","Wales","Wales","CF83","caerphilly"),
    ("Cwmbran","Wales","Wales","NP44","cwmbran"),
    ("Abergavenny","Wales","Wales","NP7","abergavenny"),
    ("Chepstow","Wales","Wales","NP16","chepstow"),
    ("Pontypool","Wales","Wales","NP4","pontypool"),
    ("Ebbw Vale","Wales","Wales","NP23","ebbw-vale"),
    ("Tredegar","Wales","Wales","NP22","tredegar"),
    ("Abertillery","Wales","Wales","NP13","abertillery"),
    ("Aberystwyth","Wales","Wales","SY23","aberystwyth"),
    ("Haverfordwest","Wales","Wales","SA61","haverfordwest"),
    ("Pembroke","Wales","Wales","SA71","pembroke"),
    ("Tenby","Wales","Wales","SA70","tenby"),
    ("Milford Haven","Wales","Wales","SA73","milford-haven"),
    ("Carmarthen","Wales","Wales","SA31","carmarthen"),
    ("Ammanford","Wales","Wales","SA18","ammanford"),
    ("Newtown Wales","Wales","Wales","SY16","newtown-wales"),
    ("Welshpool","Wales","Wales","SY21","welshpool"),
    ("Caernarfon","Wales","Wales","LL55","caernarfon"),
    ("Bangor Wales","Wales","Wales","LL57","bangor-wales"),
    ("Llandudno","Wales","Wales","LL30","llandudno"),
    ("Colwyn Bay","Wales","Wales","LL29","colwyn-bay"),
    ("Rhyl","Wales","Wales","LL18","rhyl"),
    ("Prestatyn","Wales","Wales","LL19","prestatyn"),
    ("Flint","Wales","Wales","CH6","flint"),
    ("Mold","Wales","Wales","CH7","mold"),
    ("Denbigh","Wales","Wales","LL16","denbigh"),
    ("Ruthin","Wales","Wales","LL15","ruthin"),
    ("Llangollen","Wales","Wales","LL20","llangollen"),
    ("Holyhead","Wales","Wales","LL65","holyhead"),
    ("Cardigan","Wales","Wales","SA43","cardigan"),
    ("Fishguard","Wales","Wales","SA65","fishguard"),
    ("Llandrindod Wells","Wales","Wales","LD1","llandrindod-wells"),
    ("Builth Wells","Wales","Wales","LD2","builth-wells"),
    ("Monmouth","Wales","Wales","NP25","monmouth"),
    ("Caldicot","Wales","Wales","NP26","caldicot"),
    ("Bargoed","Wales","Wales","CF81","bargoed"),
    ("Ystrad Mynach","Wales","Wales","CF82","ystrad-mynach"),
    ("Brynmawr","Wales","Wales","NP23","brynmawr"),
    ("Blaenavon","Wales","Wales","NP4","blaenavon"),
    ("Aberdare","Wales","Wales","CF44","aberdare"),
    ("Mountain Ash","Wales","Wales","CF45","mountain-ash"),
    ("Ferndale","Wales","Wales","CF43","ferndale"),
    ("Treorchy","Wales","Wales","CF42","treorchy"),
    ("Tonypandy","Wales","Wales","CF40","tonypandy"),
    ("Porth","Wales","Wales","CF39","porth"),
    ("Port Talbot","Wales","Wales","SA13","port-talbot"),
    ("Briton Ferry","Wales","Wales","SA11","briton-ferry"),
    ("Skewen","Wales","Wales","SA10","skewen"),
    ("Pontardawe","Wales","Wales","SA8","pontardawe"),
    ("Clydach","Wales","Wales","SA6","clydach"),
    ("Morriston","Wales","Wales","SA6","morriston"),
    ("Sketty","Wales","Wales","SA2","sketty"),
    ("Mumbles","Wales","Wales","SA3","mumbles"),
    ("Gorseinon","Wales","Wales","SA4","gorseinon"),
    ("Llandeilo","Wales","Wales","SA19","llandeilo"),
    ("Ystradgynlais","Wales","Wales","SA9","ystradgynlais"),
    ("Maesteg","Wales","Wales","CF34","maesteg"),
    ("Porthcawl","Wales","Wales","CF36","porthcawl"),
    ("Pencoed","Wales","Wales","CF35","pencoed"),
    ("Pontyclun","Wales","Wales","CF72","pontyclun"),
    ("Church Village","Wales","Wales","CF38","church-village"),
    ("Roath","Wales","Wales","CF24","roath"),
    ("Penylan","Wales","Wales","CF23","penylan"),
    ("Llanishen","Wales","Wales","CF14","llanishen"),
    ("Canton","Wales","Wales","CF5","canton"),
    ("Llandaff","Wales","Wales","CF5","llandaff"),
    ("Fairwater","Wales","Wales","CF5","fairwater"),
    ("Whitchurch Cardiff","Wales","Wales","CF14","whitchurch-cardiff"),
    ("Rhiwbina","Wales","Wales","CF14","rhiwbina"),
    ("Splott","Wales","Wales","CF24","splott"),
    ("Grangetown Cardiff","Wales","Wales","CF11","grangetown-cardiff"),
    ("Taffs Well","Wales","Wales","CF15","taffs-well"),
    ("Radyr","Wales","Wales","CF15","radyr"),
    ("Dinas Powys","Wales","Wales","CF64","dinas-powys"),
    ("Sully","Wales","Wales","CF64","sully"),
    ("St Fagans","Wales","Wales","CF5","st-fagans"),
    ("Pentwyn","Wales","Wales","CF23","pentwyn"),
    ("Llanrumney","Wales","Wales","CF3","llanrumney"),
    ("St Mellons","Wales","Wales","CF3","st-mellons"),
    # ── NORTHERN IRELAND ──────────────────────────────────────────────────────
    ("Belfast","Northern Ireland","Northern Ireland","BT1","belfast"),
    ("Derry","Northern Ireland","Northern Ireland","BT48","derry"),
    ("Lisburn","Northern Ireland","Northern Ireland","BT28","lisburn"),
    ("Newry","Northern Ireland","Northern Ireland","BT34","newry"),
    ("Armagh","Northern Ireland","Northern Ireland","BT61","armagh"),
    ("Omagh","Northern Ireland","Northern Ireland","BT78","omagh"),
    ("Dungannon","Northern Ireland","Northern Ireland","BT71","dungannon"),
    ("Coleraine","Northern Ireland","Northern Ireland","BT52","coleraine"),
    ("Ballymena","Northern Ireland","Northern Ireland","BT43","ballymena"),
    ("Antrim","Northern Ireland","Northern Ireland","BT41","antrim"),
    ("Larne","Northern Ireland","Northern Ireland","BT40","larne"),
    ("Carrickfergus","Northern Ireland","Northern Ireland","BT38","carrickfergus"),
    ("Newtownabbey","Northern Ireland","Northern Ireland","BT36","newtownabbey"),
    ("Bangor NI","Northern Ireland","Northern Ireland","BT20","bangor-ni"),
    ("Newtownards","Northern Ireland","Northern Ireland","BT23","newtownards"),
    ("Downpatrick","Northern Ireland","Northern Ireland","BT30","downpatrick"),
    ("Banbridge","Northern Ireland","Northern Ireland","BT32","banbridge"),
    ("Enniskillen","Northern Ireland","Northern Ireland","BT74","enniskillen"),
    ("Strabane","Northern Ireland","Northern Ireland","BT82","strabane"),
    ("Limavady","Northern Ireland","Northern Ireland","BT49","limavady"),
    ("Portrush","Northern Ireland","Northern Ireland","BT56","portrush"),
    ("Ballymoney","Northern Ireland","Northern Ireland","BT53","ballymoney"),
    ("Cookstown","Northern Ireland","Northern Ireland","BT80","cookstown"),
    ("Magherafelt","Northern Ireland","Northern Ireland","BT45","magherafelt"),
    ("Holywood","Northern Ireland","Northern Ireland","BT18","holywood"),
    ("Warrenpoint","Northern Ireland","Northern Ireland","BT34","warrenpoint"),
    ("Glengormley","Northern Ireland","Northern Ireland","BT36","glengormley"),
    ("Carryduff","Northern Ireland","Northern Ireland","BT8","carryduff"),
    ("Dundonald","Northern Ireland","Northern Ireland","BT16","dundonald"),
    ("Comber","Northern Ireland","Northern Ireland","BT23","comber"),
    ("Ballynahinch","Northern Ireland","Northern Ireland","BT24","ballynahinch"),
    ("Ballyclare","Northern Ireland","Northern Ireland","BT39","ballyclare"),
    ("Randalstown","Northern Ireland","Northern Ireland","BT41","randalstown"),
    ("Castlederg","Northern Ireland","Northern Ireland","BT81","castlederg"),
    ("Maghera","Northern Ireland","Northern Ireland","BT46","maghera"),
    ("Dromore NI","Northern Ireland","Northern Ireland","BT25","dromore-ni"),
    ("Hillsborough","Northern Ireland","Northern Ireland","BT26","hillsborough"),
    ("Portstewart","Northern Ireland","Northern Ireland","BT55","portstewart"),
    ("Greenisland","Northern Ireland","Northern Ireland","BT38","greenisland"),
    ("Whitehead","Northern Ireland","Northern Ireland","BT38","whitehead"),
    ("Ballycastle","Northern Ireland","Northern Ireland","BT54","ballycastle"),
    ("Crumlin","Northern Ireland","Northern Ireland","BT29","crumlin"),
    ("Coalisland","Northern Ireland","Northern Ireland","BT71","coalisland"),
    ("Fivemiletown","Northern Ireland","Northern Ireland","BT75","fivemiletown"),
    ("Saintfield","Northern Ireland","Northern Ireland","BT24","saintfield"),
    ("Finaghy","Northern Ireland","Northern Ireland","BT10","finaghy"),
    ("Dunmurry","Northern Ireland","Northern Ireland","BT17","dunmurry"),
    ("Stranmillis","Northern Ireland","Northern Ireland","BT9","stranmillis"),
    ("Malone","Northern Ireland","Northern Ireland","BT9","malone"),
    ("Jordanstown","Northern Ireland","Northern Ireland","BT37","jordanstown"),
]


def build_db(output_path="data/locations.json"):
    """Deduplicate by slug and save to JSON."""
    seen = set()
    unique = []
    for loc in ALL_LOCATIONS:
        slug = loc[4]
        if slug not in seen:
            seen.add(slug)
            unique.append(list(loc))

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(unique, f, indent=2)

    print(f"✅  {len(unique)} unique locations saved to {output_path}")
    return unique


if __name__ == "__main__":
    build_db()
